// ignore_for_file: constant_identifier_names

List bedTitle = [
"امبولی هوا",
"راه های هوایی و ونتیلاتورها",
"خونریزی بعد از زایمان",
"لخته شدن خون",
"عفونت دستگاه ادراری مرتبط با کاتتر (CAUTI)",
"عفونت جریان خون اکتسابی خط مرکزی (CLABSI)",
"عفونت Clostridioides difficile (C. diff)",
"کووید 19",
"هذیان",
"طرح تخلیه",
"تحرک اولیه",
"پنومونی اکتسابی در بیمارستان",
"بیماری قلبی نوزاد",
"پیشگیری از عفونت",
"سپسیس مادر",
"اشتباهات پزشکی",
"دارو در خانه",
"مدیریت درد",
"پره اکلامپسی",
"سوالاتی برای پزشک و پرستار شما",
"منابع",
"سپسیس",
"سپسیس در نوزادان و کودکان",
"کاهش استرس",
"خودکشی کردن",
"عفونت های جراحی",
"تغذیه لوله",
"واکسیناسیون ها",
];

List bedSubTitle = [
  "انسداد هوای جریان خون",
  "کمک به تنفس",
  "خونریزی پس از زایمان",
  "ترومبوآمبولی ورید (TEV)",
  "عفونت مجاری ادراری از کاتتر",
  "عفونت خون از کاتتر مرکزی",
  "عفونت شدید اسهالی",
  "آنچه شما باید بدانید",
  "گیجی شدید ناگهانی",
  "قبل از ترک بیمارستان",
  "بیرون آمدن ایمن از رختخواب",
  "پنومونی از بیمارستان",
  "بیماری قلبی مادرزادی بحرانی",
  "چگونه از عفونت جلوگیری کنیم",
  "سپسیس قبل، حین و بعد از بارداری",
  "دنبال چه چیزی میگردی",
  "ایمنی دارو در خانه",
  "پیشگیری از افسردگی تنفسی",
  "وضعیت جدی بارداری و پس از زایمان",
  "با پرسیدن سوال یاد بگیرید",
  "پیوندها به منابع",
  "واکنش بیش از حد خطرناک به عفونت",
  "واکنش بیش از حد خطرناک به عفونت",
  "راه هایی برای آرامش",
  "بحران سلامت روان",
  "عفونت های بعد از جراحی",
  "حمایت های تغذیه ای",
  "پیشگیری از عفونت",
];

List bedImages = [
  "./assets/images/ae.svg",
  "./assets/images/aav.svg",
  "./assets/images/bab.svg",
  "./assets/images/bc.svg",
  "./assets/images/cauti.svg",
  "./assets/images/clabsi.svg",
  "./assets/images/cdiff.svg",
  "./assets/images/covid.svg",
  "./assets/images/d.svg",
  "./assets/images/dp.svg",
  "./assets/images/em.svg",
  "./assets/images/hap.svg",
  "./assets/images/bd.svg",
  "./assets/images/ip.svg",
  "./assets/images/ms.svg",
  "./assets/images/mm.svg",
  "./assets/images/mah.svg",
  "./assets/images/pm.svg",
  "./assets/images/p.svg",
  "./assets/images/q.svg",
  "./assets/images/r.svg",
  "./assets/images/s.svg",
  "./assets/images/sbc.svg",
  "./assets/images/sr.svg",
  "./assets/images/su.svg",
  "./assets/images/si.svg",
  "./assets/images/tf.svg",
  "./assets/images/v.svg",
];

List bedRoute = [
  'ae',
  'aav',
  'bat',
  'bc',
  'cauti',
  'clabsi',
  'cdiff',
  'covid',
  'd',
  'dp',
  'em',
  'hap',
  'bd',
  'ip',
  'ms',
  'mm',
  'mah',
  'pm',
  'p',
  'q',
  'r',
  's',
  'sbc',
  'sr',
  'su',
  'si',
  'tf',
  'v',
];
