// ignore_for_file: constant_identifier_names

List homeTitle = [
"امبولی هوا",
"راه های هوایی و ونتیلاتورها",
"کم خونی و انتقال خون",
"لخته شدن خون",
"عفونت جریان خون اکتسابی خط مرکزی (CLABSI)",
"کووید 19",
"تحرک اولیه",
"تیم مراقبت های بهداشتی",
"اطلاعات بیمارستان",
"پنومونی اکتسابی در بیمارستان",
"پیشگیری از عفونت",
"سپسیس مادر",
"اشتباهات پزشکی",
"دارو در خانه",
"خطاهای دارویی",
"مدیریت درد",
"پره اکلامپسی",
"سوالاتی برای پزشک و پرستار شما",
"منابع",
"سپسیس",
"سپسیس در نوزادان و کودکان",
"کاهش استرس",
"خودکشی کردن",
"عفونت های جراحی",
"واکسیناسیون ها",
"علائم حیاتی و مانیتورها",
];

List homeSubTitle = [
  "انسداد هوای جریان خون",
  "کمک به تنفس",
  "کم خونی و انتقال خون",
  "ترومبوآمبولی ورید (TEV)",
  "عفونت خون از کاتتر مرکزی",
  "آنچه شما باید بدانید",
  "بیرون آمدن ایمن از رختخواب",
  "Who's Who در بیمارستان",
  "راهنمای بیمارستان بیماران",
  "پنومونی از بیمارستان",
  "چگونه از عفونت جلوگیری کنیم",
  "سپسیس قبل، حین و بعد از بارداری",
  "دنبال چه چیزی میگردی",
  "ایمنی دارو در خانه",
  "اشتباهات انجام شده با داروها",
  "پیشگیری از افسردگی تنفسی",
  "وضعیت جدی بارداری و پس از زایمان",
  "با پرسیدن سوال یاد بگیرید",
  "پیوندها به منابع",
  "واکنش بیش از حد خطرناک به عفونت",
  "واکنش بیش از حد خطرناک به عفونت",
  "راه هایی برای آرامش",
  "بحران سلامت روان",
  "عفونت های بعد از جراحی",
  "پیشگیری از عفونت",
  "نظارت بر بیمار",
];

List homeImages = [
  "./assets/images/ae.svg",
  "./assets/images/aav.svg",
  "./assets/images/abt.svg",
  "./assets/images/bc.svg",
  "./assets/images/clabsi.svg",
  "./assets/images/covid.svg",
  "./assets/images/em.svg",
  "./assets/images/ht.svg",
  "./assets/images/hi.svg",
  "./assets/images/hap.svg",
  "./assets/images/ip.svg",
  "./assets/images/ms.svg",
  "./assets/images/mm.svg",
  "./assets/images/mah.svg",
  "./assets/images/me.svg",
  "./assets/images/pm.svg",
  "./assets/images/p.svg",
  "./assets/images/q.svg",
  "./assets/images/r.svg",
  "./assets/images/s.svg",
  "./assets/images/sbc.svg",
  "./assets/images/sr.svg",
  "./assets/images/su.svg",
  "./assets/images/si.svg",
  "./assets/images/v.svg",
  "./assets/images/vsm.svg",
];
