// ignore_for_file: constant_identifier_names

import 'package:patient_aider/views/screens/topic_screens/vsm.dart';

List hosTitle = [
"امبولی هوا",
"راه های هوایی و ونتیلاتورها",
"کم خونی و انتقال خون",
"خونریزی بعد از زایمان",
"لخته شدن خون",
"عفونت دستگاه ادراری مرتبط با کاتتر (CAUTI)",
"عفونت جریان خون اکتسابی خط مرکزی (CLABSI)",
"عفونت کلستریدیوئید دیفیسیل (C. diff)",
"کووید 19",
"هذیان",
"طرح تخلیه",
"تحرک اولیه",
"سقوط",
"تیم مراقبت های بهداشتی",
"دور تیم مراقبت های بهداشتی با بیمار",
"اطلاعات بیمارستان",
"پنومونی اکتسابی در بیمارستان",
"بیماری قلبی نوزاد",
"پیشگیری از عفونت",
"اقدامات احتیاطی جداسازی",
"سپسیس مادر",
"اشتباهات پزشکی",
"دارو در خانه",
"خطاهای دارویی",
"مدیریت درد",
"سندرم پس از مراقبت های ویژه",
"پره اکلامپسی",
"Preemies و اکسیژن",
"سوالاتی برای پزشک و پرستار شما",
"منابع",
"سپسیس",
"سپسیس در نوزادان و کودکان",
"کاهش استرس",
"خودکشی کردن",
"عفونت های جراحی",
"تغذیه لوله",
"واکسیناسیون ها",
"علائم حیاتی و مانیتورها",
];

List hosSubTitle = [
  "انسداد هوای جریان خون",
  "کمک به تنفس",
  "کم خونی و انتقال خون",
  "خون ریزی پس از زایمان",
  "ترومبوآمبولی ورید (TEV)",
  "عفونت مجاری ادراری از کاتتر",
  "عفونت خون از کاتتر مرکزی",
  "عفونت شدید اسهالی",
  "آنچه شما باید بدانید",
  "گیجی شدید ناگهانی",
  "قبل از ترک بیمارستان",
  "بیرون آمدن ایمن از رختخواب",
  "رایج ترین رویداد بیمارستانی",
  "Who's Who در بیمارستان",
  "جمع کردن تیم و بیمار با هم",
  "راهنمای بیمارستان بیماران",
  "پنومونی از بیمارستان",
  "بیماری قلبی مادرزادی بحرانی",
  "چگونه از عفونت جلوگیری کنیم",
  "موانع بین افراد و میکروب ها",
  "سپسیس قبل، حین و بعد از بارداری",
  "دنبال چه چیزی میگردی",
  "ایمنی دارو در خانه",
  "اشتباهات مرتکب شده با داروها",
  "پیشگیری از افسردگی تنفسی",
  "چالش های جسمی و ذهنی بعد از ICU",
  "وضعیت جدی بارداری و پس از زایمان",
  "اکسیژن خیلی زیاد یا خیلی کم",
  "با پرسیدن سوال یاد بگیرید",
  "پیوندها به منابع",
  "واکنش بیش از حد خطرناک به عفونت",
  "واکنش بیش از حد خطرناک به عفونت",
  "راه هایی برای آرامش",
  "بحران سلامت روان",
  "عفونت های بعد از جراحی",
  "حمایت های تغذیه ای",
  "پیشگیری از عفونت",
  "نظارت بر بیمار",
];

List hosImages = [
  "./assets/images/ae.svg",
  "./assets/images/aav.svg",
  "./assets/images/abt.svg",
  "./assets/images/bab.svg",
  "./assets/images/bc.svg",
  "./assets/images/cauti.svg",
  "./assets/images/clabsi.svg",
  "./assets/images/cdiff.svg",
  "./assets/images/covid.svg",
  "./assets/images/d.svg",
  "./assets/images/dp.svg",
  "./assets/images/em.svg",
  "./assets/images/f.svg",
  "./assets/images/ht.svg",
  "./assets/images/htrp.svg",
  "./assets/images/hi.svg",
  "./assets/images/hap.svg",
  "./assets/images/bd.svg",
  "./assets/images/ip.svg",
  "./assets/images/isp.svg",
  "./assets/images/pm.svg",
  "./assets/images/mm.svg",
  "./assets/images/mah.svg",
  "./assets/images/me.svg",
  "./assets/images/pm.svg",
  "./assets/images/pics.svg",
  "./assets/images/p.svg",
  "./assets/images/po.svg",
  "./assets/images/q.svg",
  "./assets/images/r.svg",
  "./assets/images/s.svg",
  "./assets/images/sbc.svg",
  "./assets/images/sr.svg",
  "./assets/images/su.svg",
  "./assets/images/si.svg",
  "./assets/images/tf.svg",
  "./assets/images/v.svg",
  "./assets/images/vsm.svg",
];

List hosRoute = [
  'ae',
  'aav',
  'abt',
  'ae',
  'ae',
  'ae',
  'ae',
  'ae',
  'ae',
  'ae',
  'ae',
  'ae',
  'ae',
  'ae',
  'ae',
  'ae',
  'ae',
  'ae',
  'ae',
  'ae',
  'ae',
  'ae',
  'ae',
  'ae',
  'ae',
  'ae',
  'ae',
  'ae',
  'ae',
  'ae',
  'ae',
  'ae',
  'ae',
  'ae',
  'ae',
  'ae',
  'ae',
  'ae',
];
